In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Loading the documents

In [5]:
raw_data = pd.read_csv('Flanker task survey - pilot_July 8, 2023_19.47.csv')
raw_data

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,...,State_Anxiety_12.3,State_Anxiety_13.3,State_Anxiety_14.3,State_Anxiety_15.3,AttentionCheck_A.3,State_Anxiety_16.3,State_Anxiety_17.3,State_Anxiety_18.3,State_Anxiety_19.3,State_Anxiety_20.3
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,...,A number of statements which people have used ...,A number of statements which people have used ...,A number of statements which people have used ...,A number of statements which people have used ...,A number of statements which people have used ...,A number of statements which people have used ...,A number of statements which people have used ...,A number of statements which people have used ...,A number of statements which people have used ...,A number of statements which people have used ...
1,"{""ImportId"":""startDate"",""timeZone"":""Asia/Calcu...","{""ImportId"":""endDate"",""timeZone"":""Asia/Calcutta""}","{""ImportId"":""status""}","{""ImportId"":""ipAddress""}","{""ImportId"":""progress""}","{""ImportId"":""duration""}","{""ImportId"":""finished""}","{""ImportId"":""recordedDate"",""timeZone"":""Asia/Ca...","{""ImportId"":""_recordId""}","{""ImportId"":""recipientLastName""}",...,"{""ImportId"":""QID37_38""}","{""ImportId"":""QID37_39""}","{""ImportId"":""QID37_40""}","{""ImportId"":""QID37_41""}","{""ImportId"":""QID37_47""}","{""ImportId"":""QID37_42""}","{""ImportId"":""QID37_43""}","{""ImportId"":""QID37_44""}","{""ImportId"":""QID37_45""}","{""ImportId"":""QID37_46""}"
2,2023-07-07 13:49:05,2023-07-07 15:39:30,IP Address,202.3.77.209,100,6624,True,2023-07-07 15:39:30,R_sHa8z57DqaOUVmF,NaN,...,Not at all,Not at all,Not at all,Very much so,Very much so,Moderately so,Not at all,Not at all,Very much so,Very much so
3,2023-07-08 15:36:45,2023-07-08 18:15:14,IP Address,202.3.77.209,100,9508,True,2023-07-08 18:15:15,R_1Cd6VkTgu3tEwsu,NaN,...,Not at all,Not at all,Not at all,Somewhat,Very much so,Somewhat,Somewhat,Somewhat,Somewhat,Moderately so

In [11]:
column_names = raw_data.columns.values.tolist()
print(column_names)

print(column_names.index('Trait_Anxiety_01'))
print(column_names.index('State_Anxiety_01'))

['StartDate', 'EndDate', 'Status', 'IPAddress', 'Progress', 'Duration (in seconds)', 'Finished', 'RecordedDate', 'ResponseId', 'RecipientLastName', 'RecipientFirstName', 'RecipientEmail', 'ExternalReference', 'LocationLatitude', 'LocationLongitude', 'DistributionChannel', 'UserLanguage', 'IC_India', 'Participant ID', 'Q33', 'Q34', 'Trait_Anxiety_01', 'Trait_Anxiety_02', 'Trait_Anxiety_03', 'Trait_Anxiety_04', 'Trait_Anxiety_05', 'Trait_Anxiety_06', 'Trait_Anxiety_07', 'Trait_Anxiety_08', 'Trait_Anxiety_09', 'AttentionCheck_B', 'Trait_Anxiety_10', 'Trait_Anxiety_11', 'Trait_Anxiety_12', 'Trait_Anxiety_13', 'Trait_Anxiety_14', 'Trait_Anxiety_15', 'Trait_Anxiety_16', 'Trait_Anxiety_17', 'Trait_Anxiety_18', 'Trait_Anxiety_19', 'Trait_Anxiety_20', 'State_Anxiety_01', 'State_Anxiety_02', 'State_Anxiety_03', 'State_Anxiety_04', 'State_Anxiety_05', 'State_Anxiety_06', 'State_Anxiety_07', 'State_Anxiety_08', 'State_Anxiety_09', 'State_Anxiety_10', 'State_Anxiety_11', 'State_Anxiety_12', 'State_Anxiety_13', 'State_Anxiety_14', 'State_Anxiety_15', 'AttentionCheck_A', 'State_Anxiety_16', 'State_Anxiety_17', 'State_Anxiety_18', 'State_Anxiety_19', 'State_Anxiety_20', 'flanker1', 'State_Anxiety_01.1', 'State_Anxiety_02.1', 'State_Anxiety_03.1', 'State_Anxiety_04.1', 'State_Anxiety_05.1', 'State_Anxiety_06.1', 'State_Anxiety_07.1', 'State_Anxiety_08.1', 'State_Anxiety_09.1', 'State_Anxiety_10.1', 'State_Anxiety_11.1', 'State_Anxiety_12.1', 'State_Anxiety_13.1', 'State_Anxiety_14.1', 'State_Anxiety_15.1', 'AttentionCheck_A.1', 'State_Anxiety_16.1', 'State_Anxiety_17.1', 'State_Anxiety_18.1', 'State_Anxiety_19.1', 'State_Anxiety_20.1', 'State_Anxiety_01.2', 'State_Anxiety_02.2', 'State_Anxiety_03.2', 'State_Anxiety_04.2', 'State_Anxiety_05.2', 'State_Anxiety_06.2', 'State_Anxiety_07.2', 'State_Anxiety_08.2', 'State_Anxiety_09.2', 'State_Anxiety_10.2', 'State_Anxiety_11.2', 'State_Anxiety_12.2', 'State_Anxiety_13.2', 'State_Anxiety_14.2', 'State_Anxiety_15.2', 'AttentionCheck_A.2', 'State_Anxiety_16.2', 'State_Anxiety_17.2', 'State_Anxiety_18.2', 'State_Anxiety_19.2', 'State_Anxiety_20.2', 'State_Anxiety_01.3', 'State_Anxiety_02.3', 'State_Anxiety_03.3', 'State_Anxiety_04.3', 'State_Anxiety_05.3', 'State_Anxiety_06.3', 'State_Anxiety_07.3', 'State_Anxiety_08.3', 'State_Anxiety_09.3', 'State_Anxiety_10.3', 'State_Anxiety_11.3', 'State_Anxiety_12.3', 'State_Anxiety_13.3', 'State_Anxiety_14.3', 'State_Anxiety_15.3', 'AttentionCheck_A.3', 'State_Anxiety_16.3', 'State_Anxiety_17.3', 'State_Anxiety_18.3', 'State_Anxiety_19.3', 'State_Anxiety_20.3']
21
42

In [16]:
trait_anx = raw_data.iloc[2:, 21:42]

In [18]:
print(trait_anx.columns.values.tolist())

['Trait_Anxiety_01', 'Trait_Anxiety_02', 'Trait_Anxiety_03', 'Trait_Anxiety_04', 'Trait_Anxiety_05', 'Trait_Anxiety_06', 'Trait_Anxiety_07', 'Trait_Anxiety_08', 'Trait_Anxiety_09', 'AttentionCheck_B', 'Trait_Anxiety_10', 'Trait_Anxiety_11', 'Trait_Anxiety_12', 'Trait_Anxiety_13', 'Trait_Anxiety_14', 'Trait_Anxiety_15', 'Trait_Anxiety_16', 'Trait_Anxiety_17', 'Trait_Anxiety_18', 'Trait_Anxiety_19', 'Trait_Anxiety_20']

In [23]:
pre_attention = trait_anx.iloc[:, :9]
post_attention = trait_anx.iloc[:, 10:]

In [24]:
pre_attention

,Trait_Anxiety_01,Trait_Anxiety_02,Trait_Anxiety_03,Trait_Anxiety_04,Trait_Anxiety_05,Trait_Anxiety_06,Trait_Anxiety_07,Trait_Anxiety_08,Trait_Anxiety_09
2,Almost Always,Sometimes,Often,Sometimes,Sometimes,Often,Almost Always,Sometimes,Almost never
3,Sometimes,Sometimes,Almost never,Almost never,Sometimes,Almost never,Often,Sometimes,Almost never

In [25]:
post_attention

,Trait_Anxiety_10,Trait_Anxiety_11,Trait_Anxiety_12,Trait_Anxiety_13,Trait_Anxiety_14,Trait_Anxiety_15,Trait_Anxiety_16,Trait_Anxiety_17,Trait_Anxiety_18,Trait_Anxiety_19,Trait_Anxiety_20
2,Often,Almost never,Sometimes,Often,Sometimes,Sometimes,Often,Almost Always,Almost never,Often,Sometimes
3,Sometimes,Almost never,Sometimes,Almost never,Sometimes,Almost never,Almost never,Almost never,Almost never,Almost never,Sometimes

In [28]:
trait_anx = pd.concat([pre_attention, post_attention], axis=1)

In [29]:
trait_anx

,Trait_Anxiety_01,Trait_Anxiety_02,Trait_Anxiety_03,Trait_Anxiety_04,Trait_Anxiety_05,Trait_Anxiety_06,Trait_Anxiety_07,Trait_Anxiety_08,Trait_Anxiety_09,Trait_Anxiety_10,Trait_Anxiety_11,Trait_Anxiety_12,Trait_Anxiety_13,Trait_Anxiety_14,Trait_Anxiety_15,Trait_Anxiety_16,Trait_Anxiety_17,Trait_Anxiety_18,Trait_Anxiety_19,Trait_Anxiety_20
2,Almost Always,Sometimes,Often,Sometimes,Sometimes,Often,Almost Always,Sometimes,Almost never,Often,Almost never,Sometimes,Often,Sometimes,Sometimes,Often,Almost Always,Almost never,Often,Sometimes
3,Sometimes,Sometimes,Almost never,Almost never,Sometimes,Almost never,Often,Sometimes,Almost never,Sometimes,Almost never,Sometimes,Almost never,Sometimes,Almost never,Almost never,Almost never,Almost never,Almost never,Sometimes

In [31]:
trait_index_list = [0, 2, 5, 6, 9, 12, 13, 15, 18] # 'Almost Never': Bad
rev_trait_index_list = [1, 3, 4, 7, 8, 10, 11, 14, 16, 17, 19] # 'Almost Never': Good

In [33]:
trait_df = trait_anx.iloc[:, trait_index_list]
rev_trait_df = trait_anx.iloc[:, rev_trait_index_list]

In [34]:
trait_df

,Trait_Anxiety_01,Trait_Anxiety_03,Trait_Anxiety_06,Trait_Anxiety_07,Trait_Anxiety_10,Trait_Anxiety_13,Trait_Anxiety_14,Trait_Anxiety_16,Trait_Anxiety_19
2,Almost Always,Often,Often,Almost Always,Often,Often,Sometimes,Often,Often
3,Sometimes,Almost never,Almost never,Often,Sometimes,Almost never,Sometimes,Almost never,Almost never

In [35]:
rev_trait_df

,Trait_Anxiety_02,Trait_Anxiety_04,Trait_Anxiety_05,Trait_Anxiety_08,Trait_Anxiety_09,Trait_Anxiety_11,Trait_Anxiety_12,Trait_Anxiety_15,Trait_Anxiety_17,Trait_Anxiety_18,Trait_Anxiety_20
2,Sometimes,Sometimes,Sometimes,Sometimes,Almost never,Almost never,Sometimes,Sometimes,Almost Always,Almost never,Sometimes
3,Sometimes,Almost never,Sometimes,Sometimes,Almost never,Almost never,Sometimes,Almost never,Almost never,Almost never,Sometimes

In [51]:
mapping= dict(zip(["Almost never","Sometimes","Often","Almost Always"],[4,3,2,1]))
trait_df = trait_df.replace(mapping)
trait_df

,Trait_Anxiety_01,Trait_Anxiety_03,Trait_Anxiety_06,Trait_Anxiety_07,Trait_Anxiety_10,Trait_Anxiety_13,Trait_Anxiety_14,Trait_Anxiety_16,Trait_Anxiety_19
2,1,2,2,1,2,2,3,2,2
3,3,4,4,2,3,4,3,4,4

In [52]:
rev_mapping = dict(zip(["Almost never","Sometimes","Often","Almost Always"],[1,2,3,4]))
rev_trait_df = rev_trait_df.replace(rev_mapping)
rev_trait_df

,Trait_Anxiety_02,Trait_Anxiety_04,Trait_Anxiety_05,Trait_Anxiety_08,Trait_Anxiety_09,Trait_Anxiety_11,Trait_Anxiety_12,Trait_Anxiety_15,Trait_Anxiety_17,Trait_Anxiety_18,Trait_Anxiety_20
2,2,2,2,2,1,1,2,2,4,1,2
3,2,1,2,2,1,1,2,1,1,1,2

In [43]:
trait_anx_score = trait_df.sum(axis = 1)

In [44]:
trait_anx_score

2    17
3    31
dtype: int64

In [45]:
rev_trait_anx_score = rev_trait_df.sum(axis = 1)

In [46]:
rev_trait_anx_score

2    21
3    16
dtype: int64

In [47]:
trait_anx_score_lst = trait_anx_score.to_list()

In [48]:
rev_trait_anx_score_lst = rev_trait_anx_score.to_list()

In [49]:
total_trait_anx_score = [trait_anx_score_lst[x] + rev_trait_anx_score_lst[x] for x in range(len(trait_anx_score_lst))]

In [50]:
total_trait_anx_score

[38, 47]

In [56]:
promit_data = pd.read_csv('trait_anx_promit_score.csv')
promit_data = promit_data.iloc[-2:, 21:42]
promit_data

,Trait_Anxiety_01,Trait_Anxiety_02,Trait_Anxiety_03,Trait_Anxiety_04,Trait_Anxiety_05,Trait_Anxiety_06,Trait_Anxiety_07,Trait_Anxiety_08,Trait_Anxiety_09,AttentionCheck_B,...,Trait_Anxiety_11,Trait_Anxiety_12,Trait_Anxiety_13,Trait_Anxiety_14,Trait_Anxiety_15,Trait_Anxiety_16,Trait_Anxiety_17,Trait_Anxiety_18,Trait_Anxiety_19,Trait_Anxiety_20
60,Often,Sometimes,Often,Often,Sometimes,Often,Sometimes,Sometimes,Sometimes,Almost Always,...,Almost never,Sometimes,Often,Sometimes,Almost never,Often,Sometimes,Almost never,Sometimes,Sometimes
61,Sometimes,Sometimes,Often,Sometimes,Sometimes,Sometimes,Sometimes,Sometimes,Sometimes,Almost Always,...,Often,Almost never,Often,Sometimes,Sometimes,Often,Sometimes,Often,Often,Almost never

In [58]:
pre_attention = promit_data.iloc[:, :9]
post_attention = promit_data.iloc[:, 10:]
trait_anx = pd.concat([pre_attention, post_attention], axis=1)
trait_df = trait_anx.iloc[:, trait_index_list]
rev_trait_df = trait_anx.iloc[:, rev_trait_index_list]
mapping= dict(zip(["Almost never","Sometimes","Often","Almost Always"],[4,3,2,1]))
trait_df = trait_df.replace(mapping)
trait_df
rev_mapping = dict(zip(["Almost never","Sometimes","Often","Almost Always"],[1,2,3,4]))
rev_trait_df = rev_trait_df.replace(rev_mapping)
rev_trait_df
trait_anx_score = trait_df.sum(axis = 1)
rev_trait_anx_score = rev_trait_df.sum(axis = 1)
trait_anx_score_lst = trait_anx_score.to_list()
rev_trait_anx_score_lst = rev_trait_anx_score.to_list()
total_trait_anx_score = [trait_anx_score_lst[x] + rev_trait_anx_score_lst[x] for x in range(len(trait_anx_score_lst))]
total_trait_anx_score

[42, 44]

In [59]:
promit_score = np.mean(total_trait_anx_score)

In [61]:
promit_score

43.0